feat: Rename commands
Signed-off-by: Rodolfo Mói de Oliveira <rodmoi.oliveira@gmail.com>

diff --git a/.local/bin/git-bump b/.local/bin/git-bump
--- a/.local/bin/git-bump
+++ b/.local/bin/git-bump
@@ -3,11 +3,12 @@
 declare TRACE
 [[ "${TRACE}" == 1 ]] && set -o xtrace
 set -o errexit
-set -o nounset
-set -o pipefail
 set -o noclobber
+set -o pipefail
+shopt -s inherit_errexit
 
 CMD_NAME="git-bump"
+CMD_DESCRIPTION="Bump the current tag version to the next version according to the semantic versioning specifications."
 
 declare DRY_RUN=false
 declare MESSAGE=''
@@ -19,12 +20,13 @@ deps-validate() {
   is_valid=true
 
   deps=(
-    "awk"
+    "cat"
+    "env"
+    "getopt"
     "git"
-    "grep"
-    "head"
-    "sed"
-    "xargs"
+    "rg"
+    "sd"
+    "tail"
   )
   for dep in "${deps[@]}"; do
     if ! command -v "${dep}" &>/dev/null; then
@@ -38,25 +40,16 @@ deps-validate() {
   if [[ "${is_valid}" == false ]]; then
     printf 1>&2 "You must install all the dependencies for %s to work correctly:\n\n" "${CMD_NAME}"
     printf 1>&2 "    %s\n" "${summary[@]}"
-
-    printf 1>&2 "\nYou can find the installation instructions for each dependency at:\n\n"
-    printf 1>&2 "     [awk] https://man7.org/linux/man-pages/man1/awk.1p.html\n"
-    printf 1>&2 "     [git] https://git-scm.com/book/en/v2/Getting-Started-Installing-Git\n"
-    printf 1>&2 "    [grep] https://man7.org/linux/man-pages/man1/grep.1.html\n"
-    printf 1>&2 "    [head] https://man7.org/linux/man-pages/man1/head.1.html\n"
-    printf 1>&2 "     [sed] https://man7.org/linux/man-pages/man1/sed.1.html\n"
-    printf 1>&2 "   [xargs] https://www.man7.org/linux/man-pages/man1/xargs.1.html\n"
     exit 1
   fi
 }
 
-usage_short() {
+usage-short() {
   local help_text
 
   help_text=$(
     cat <<EOF
-Bump the current tag version to the next version according to the semantic
-versioning specifications
+${CMD_DESCRIPTION}
 
 Usage: ${CMD_NAME} [OPTIONS] --level <RELEASE_LEVEL>
 
@@ -73,14 +66,15 @@ EOF
   printf 1>&2 "%s\n" "${help_text}"
 }
 
-usage_long() {
+usage-long() {
   local help_text
-  help_text=$(
-    cat <<"EOF"
-Bump the current tag version to the next version according to the semantic
-versioning specifications
 
-Usage: ${CMD_NAME} [OPTIONS] --level <RELEASE_LEVEL>
+  help_text=$(
+    cat <<EOF
+${CMD_DESCRIPTION}
+
+Usage:
+  ${CMD_NAME} [OPTIONS] --level <RELEASE_LEVEL>
 
 Arguments:
   -l, --level <RELEASE_LEVEL>
@@ -94,7 +88,7 @@ Options:
           Prints the next version without committing anything
 
   -h, --help
-          Print help information (use `-h` for a summary)
+          Print help information (use '-h' for a summary)
 
 Examples:
   ${CMD_NAME} -l patch -m "version %T"
@@ -106,7 +100,7 @@ EOF
   printf 1>&2 "%s\n" "${help_text}"
 }
 
-args_parse() {
+args-parse() {
   local args
 
   if ! args=$(
@@ -124,11 +118,11 @@ args_parse() {
   while [[ $# -gt 0 ]]; do
     case "$1" in
     -h)
-      usage_short
+      usage-short
       exit 0
       ;;
     --help)
-      usage_long
+      usage-long
       exit 0
       ;;
     -l | --level)
@@ -146,40 +140,40 @@ args_parse() {
       shift
       break
       ;;
-    *) usage_long ;;
+    *) usage-long ;;
     esac
     shift
   done
 }
 
-error_release() {
-  printf 1>&2 "git-bump: '%s' isn't a valid value for '--level <RELEASE_LEVEL>'\n" "${RELEASE_LEVEL}"
+error-release() {
+  printf 1>&2 "'%s' isn't a valid value for '--level <RELEASE_LEVEL>'\n" "${RELEASE_LEVEL}"
   printf 1>&2 "  [possible values: patch, minor, major]\n\n"
   printf 1>&2 "For more information try '--help'\n"
   exit 1
 }
 
-error_not_git_dir() {
+error-not-git-dir() {
   printf 1>&2 "%s is not a git repository\n" "$(pwd)"
   exit 1
 }
 
-error_no_semver() {
+error-no-semver() {
   printf 1>&2 "%s repo doesn't have any tag\n\n" "$(pwd)"
   printf 1>&2 "You can create one like this:\n"
   printf 1>&2 "git tag -a 0.1.0 -m \"version 0.1.0\"\n"
   exit 1
 }
 
-error_prerelease_buildmetadata() {
-  printf 1>&2 "git-bump: bump fail because tag '%s' has additional info.\n\n" "${CURRENT_VERSION}"
+error-prerelease-buildmetadata() {
+  printf 1>&2 "bump fail because tag '%s' has additional info.\n\n" "${CURRENT_VERSION}"
   printf 1>&2 "      prerelease: '%s'\n" "${prerelease}"
   printf 1>&2 "   buildmetadata: '%s'\n" "${buildmetadata}"
   exit 1
 }
 
-error_invalid_semver() {
-  printf 1>&2 "git-bump: last version '%s' isn't a valid semantic version tag.\n" "${CURRENT_VERSION}"
+error-invalid-semver() {
+  printf 1>&2 "last version '%s' isn't a valid semantic version tag.\n" "${CURRENT_VERSION}"
   printf 1>&2 "For more info, visit https://semver.org/\n\n"
   printf 1>&2 "You can rename the tag with:\n"
   printf 1>&2 "git tag new old\n"
@@ -187,49 +181,49 @@ error_invalid_semver() {
   exit 1
 }
 
-args_validate() {
+args-validate() {
   if [[ -z "${RELEASE_LEVEL}" && -z "${MESSAGE}" && "${DRY_RUN}" == false ]]; then
-    usage_long
+    usage-long
     exit 0
   fi
 
   if [[ -z "${RELEASE_LEVEL}" ]]; then
-    error_release
+    error-release
   fi
 }
 
-git_dir_check() {
+git-dir-check() {
   local -r is_git_dir=$(git rev-parse --git-dir 2>/dev/null)
 
   if [[ -n "${is_git_dir}" ]]; then
     CURRENT_VERSION=$(git -P tag --sort=taggerdate --format '%(tag)' | tail -n1)
   else
-    error_not_git_dir
+    error-not-git-dir
   fi
 }
 
-semver_get() {
+semver-get() {
   if [[ -z "${CURRENT_VERSION}" ]]; then
-    error_no_semver
+    error-no-semver
   fi
 }
 
-release_check() {
+release-check() {
   case "${RELEASE_LEVEL}" in
   "patch") ;;
   "minor") ;;
   "major") ;;
-  *) error_release ;;
+  *) error-release ;;
   esac
 }
 
-semver_validate() {
+semver-validate() {
   if ! printf "%s" "${CURRENT_VERSION}" | rg "${SEMVER_REGEX}" >/dev/null; then
-    error_invalid_semver
+    error-invalid-semver
   fi
 }
 
-semver_parse() {
+semver-parse() {
   # shellcheck disable=SC2016
   v=$(printf "%s" "${CURRENT_VERSION}" | sd "${SEMVER_REGEX}" '${v}')
   # shellcheck disable=SC2016
@@ -244,11 +238,11 @@ semver_parse() {
   buildmetadata=$(printf "%s" "${CURRENT_VERSION}" | sd "${SEMVER_REGEX}" '${buildmetadata}')
 
   if [[ -n "${prerelease}" || -n "${buildmetadata}" ]]; then
-    error_prerelease_buildmetadata
+    error-prerelease-buildmetadata
   fi
 }
 
-semver_bump() {
+semver-bump() {
   case "${RELEASE_LEVEL}" in
   "patch")
     patch=$((patch + 1))
@@ -262,13 +256,13 @@ semver_bump() {
     minor=0
     patch=0
     ;;
-  *) error_release ;;
+  *) error-release ;;
   esac
 
   readonly NEXT_VERSION="${v}${major}.${minor}.${patch}"
 }
 
-semver_next() {
+semver-next() {
   if ${DRY_RUN}; then
     printf 1>&2 "Current version is %s\n" "${CURRENT_VERSION}"
     printf 1>&2 "Semantic version will be bumped to %s\n" "${NEXT_VERSION}"
@@ -300,15 +294,15 @@ confirm() {
 }
 
 main() {
-  args_parse "$@"
-  args_validate
-  release_check
-  git_dir_check
-  semver_get
-  semver_validate
-  semver_parse
-  semver_bump
-  semver_next
+  args-parse "$@"
+  args-validate
+  release-check
+  git-dir-check
+  semver-get
+  semver-validate
+  semver-parse
+  semver-bump
+  semver-next
 }
 
 main "$@"
diff --git a/.local/bin/git-sync b/.local/bin/git-sync
--- a/.local/bin/git-sync
+++ b/.local/bin/git-sync
@@ -7,8 +7,8 @@ set -o noclobber
 set -o pipefail
 shopt -s inherit_errexit
 
-CMD_NAME="dfs"
-CMD_DESCRIPTION="Flatten json file with depth-first search."
+CMD_NAME="git-sync"
+CMD_DESCRIPTION="Pull the changes from the remote default branch into the local default branch."
 
 deps-validate() {
   summary=()
@@ -18,7 +18,9 @@ deps-validate() {
     "cat"
     "env"
     "getopt"
-    "node"
+    "git"
+    "realpath"
+    "sed"
   )
   for dep in "${deps[@]}"; do
     if ! command -v "${dep}" &>/dev/null; then
@@ -30,7 +32,7 @@ deps-validate() {
   done
 
   if [[ "${is_valid}" == false ]]; then
-    printf 1>&2 "You must install all the dependencies for %s to work correctly:\n\n" "${CMD_NAME}"
+    printf 1>&2 "You must install all the dependencies for %s work correctly:\n\n" "${CMD_NAME}"
     printf 1>&2 "    %s\n" "${summary[@]}"
     exit 1
   fi
@@ -46,7 +48,7 @@ ${CMD_DESCRIPTION}
 Usage: ${CMD_NAME} [OPTIONS]
 
 Options:
-  -f, --file   <FILE>     Path to a json file
+      --path   <PATH>     Use to run as if ${CMD_NAME} was started in <PATH> instead of the current working directory [default: \$(pwd)]
   -h, --help              Print help information (use '--help' for more detail)
 EOF
   )
@@ -65,14 +67,19 @@ Usage:
   ${CMD_NAME} [OPTIONS]
 
 Options:
-  -f, --file <FILE>
-          Path to a json file
+      --path <PATH>
+          Use to run as if ${CMD_NAME} was started in <PATH> instead of the current working directory
+          [default: \$(pwd)]
 
   -h, --help
           Print help information (see a summary with '-h')
 
 Examples:
-  ${CMD_NAME} --file example.json
+  ${CMD_NAME} --path ~/your/repo
+
+  # Synchronize with the latest changes in several repositories:
+  find ~/your/repo -maxdepth 1 -type d |
+    xargs -P10 -n1 ${CMD_NAME} --path
 EOF
   )
 
@@ -85,8 +92,8 @@ args-parse() {
   if ! args=$(
     getopt -a \
       -n "${CMD_NAME}" \
-      -o h,f: \
-      --long help,file: \
+      -o h \
+      --long help,path: \
       -- "$@"
   ); then
     printf 1>&2 "\nFor more information try '--help'\n"
@@ -96,9 +103,9 @@ args-parse() {
 
   while [[ $# -gt 0 ]]; do
     case "${1}" in
-    --file | -f)
+    --path)
       shift
-      FILE="${1}"
+      GIT_PATH="${1}"
       ;;
     -h)
       usage-short
@@ -119,28 +126,39 @@ args-parse() {
 }
 
 args-validate() {
-  if [[ -z "${FILE}" ]]; then
-    printf 1>&2 "error: invalid value '%s' for '--file <FILE>'\n" "${FILE}"
+  if [[ -z "${GIT_PATH}" ]]; then
+    GIT_PATH=$(pwd)
+  else
+    GIT_PATH=$(realpath "${GIT_PATH}")
+  fi
+
+  if [[ ! -d "${GIT_PATH}" ]]; then
+    printf 1>&2 "error: invalid value '%s' for '--path <PATH>'\n" "${GIT_PATH}"
     printf 1>&2 "\nFor more information try '--help'\n"
     exit 1
   fi
 
-  if [[ ! -f "${FILE}" ]]; then
-    printf 1>&2 "error: file '%s' does not exist!\n" "${FILE}"
+  if ! git -P -C "${GIT_PATH}" rev-parse --git-dir >/dev/null; then
     printf 1>&2 "\nFor more information try '--help'\n"
-    exit 1
+    exit 128
   fi
 }
 
-dfs() {
-  node "${HOME}/.local/bin/_dfs" "${FILE}"
+git-sync() {
+  # https://stackoverflow.com/questions/28666357/how-to-get-default-git-branch/44750379#44750379
+  default_branch=$(git -C "${GIT_PATH}" symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
+
+  printf -- "-------\n%s\n" "${GIT_PATH}"
+  git -C "${GIT_PATH}" stash --include-untracked
+  git -C "${GIT_PATH}" checkout "${default_branch}"
+  git -C "${GIT_PATH}" pull
 }
 
 main() {
   deps-validate
   args-parse "$@"
   args-validate
-  dfs
+  git-sync
 }
 
 main "$@"
diff --git a/.local/bin/j2b b/.local/bin/j2b
--- a/.local/bin/j2b
+++ b/.local/bin/j2b
@@ -3,10 +3,12 @@
 declare TRACE
 [[ "${TRACE}" == 1 ]] && set -o xtrace
 set -o errexit
-set -o pipefail
 set -o noclobber
+set -o pipefail
+shopt -s inherit_errexit
 
-CMD_NAME="tab-to-column"
+CMD_NAME="j2b"
+CMD_DESCRIPTION="Convert json to tab separated output."
 
 deps-validate() {
   summary=()
@@ -15,7 +17,11 @@ deps-validate() {
   deps=(
     "cat"
     "column"
-    "sed"
+    "dfs"
+    "env"
+    "getopt"
+    "node"
+    "tac"
   )
   for dep in "${deps[@]}"; do
     if ! command -v "${dep}" &>/dev/null; then
@@ -29,25 +35,21 @@ deps-validate() {
   if [[ "${is_valid}" == false ]]; then
     printf 1>&2 "You must install all the dependencies for %s to work correctly:\n\n" "${CMD_NAME}"
     printf 1>&2 "    %s\n" "${summary[@]}"
-
-    printf 1>&2 "\nYou can find the installation instructions for each dependency at:\n\n"
-    printf 1>&2 "     [cat] https://man7.org/linux/man-pages/man1/cat.1.html\n"
-    printf 1>&2 "  [column] https://man7.org/linux/man-pages/man1/column.1.html\n"
-    printf 1>&2 "     [sed] https://man7.org/linux/man-pages/man1/sed.1p.html\n"
     exit 1
   fi
 }
 
-usage_short() {
+usage-short() {
   local help_text
 
   help_text=$(
     cat <<EOF
-Display tab separated output in columns.
+${CMD_DESCRIPTION}
 
-Usage: cat file.tab | ${CMD_NAME}
+Usage: ${CMD_NAME} [OPTIONS]
 
 Options:
+  -f, --file   <FILE>     Path to a json file
   -h, --help              Print help information (use '--help' for more detail)
 EOF
   )
@@ -55,22 +57,25 @@ EOF
   printf 1>&2 "%s\n" "${help_text}"
 }
 
-usage_long() {
+usage-long() {
   local help_text
 
   help_text=$(
     cat <<EOF
-Display tab separated output in columns.
+${CMD_DESCRIPTION}
 
 Usage:
-  cat file.tab | ${CMD_NAME}
+  ${CMD_NAME} [OPTIONS]
 
 Options:
+  -f, --file <FILE>
+          Path to a json file
+
   -h, --help
           Print help information (see a summary with '-h')
 
 Examples:
-  bfs --file example.json | ${CMD_NAME}
+  ${CMD_NAME} --file example.json
 EOF
   )
 
@@ -94,34 +99,54 @@ args-parse() {
 
   while [[ $# -gt 0 ]]; do
     case "${1}" in
+    --file | -f)
+      shift
+      FILE="${1}"
+      ;;
     -h)
-      usage_short
+      usage-short
       exit 0
       ;;
     --help)
-      usage_long
+      usage-long
       exit 0
       ;;
     --)
       shift
       break
       ;;
-    *) usage_long ;;
+    *) usage-long ;;
     esac
     shift
   done
 }
 
-tab-to-column() {
-  cat - |
-    sed -E 's/\t/⨳/g' |
-    column -s "⨳" -t
+args-validate() {
+  if [[ -z "${FILE}" ]]; then
+    printf 1>&2 "error: invalid value '%s' for '--file <FILE>'\n" "${FILE}"
+    printf 1>&2 "\nFor more information try '--help'\n"
+    exit 1
+  fi
+
+  if [[ ! -f "${FILE}" ]]; then
+    printf 1>&2 "error: file '%s' does not exist!\n" "${FILE}"
+    printf 1>&2 "\nFor more information try '--help'\n"
+    exit 1
+  fi
+}
+
+j2b() {
+  {
+    dfs --file "${FILE}"
+  } | b2c |
+    tac
 }
 
 main() {
   deps-validate
   args-parse "$@"
-  tab-to-column "$@"
+  args-validate
+  j2b
 }
 
 main "$@"
