feat: add mirror-postroll
Signed-off-by: Rodolfo Mói de Oliveira <rodmoi.oliveira@gmail.com>

diff --git a/.local/bin/mirrors b/.local/bin/mirrors
--- a/.local/bin/mirrors
+++ b/.local/bin/mirrors
@@ -8,6 +8,7 @@ set -o noclobber
 shopt -s inherit_errexit
 
 DIR_MIRRORS="${BKP1}/mirrors"
+DIR_POSTROLL="${DIR_MIRRORS}/postroll"
 FILE_MIRRORS_LOG="${HOME}/MIRRORS_BACKUP_LOG"
 
 check_host() {
@@ -17,7 +18,7 @@ check_host() {
   fi
 }
 
-mirrors() {
+mirror-sites() {
   date=$(date '+%Y/%m/%d %H:%M:%S')
 
   if [[ ! -d "${DIR_MIRRORS}" ]]; then
@@ -47,9 +48,46 @@ mirrors() {
   printf -- '----\n' | tee -a "${FILE_MIRRORS_LOG}"
 }
 
+mirror-postroll() {
+  date=$(date '+%Y/%m/%d %H:%M:%S')
+
+  if [[ ! -d "${DIR_POSTROLL}" ]]; then
+    printf "%s ERROR: %s not found!\n" "${date}" "${DIR_POSTROLL}" >>"${FILE_MIRRORS_LOG}"
+    exit 1
+  fi
+
+  curl --no-progress-meter https://rm-o.dev/postroll/ |
+    grep -E 'href="(.+)"' -o |
+    sed -e 's/href=//g' -e 's/"//g' |
+    grep '\(rm-o\|creative\|stripe\|github\|linkedin\|mastodon\)' -v |
+    grep http |
+    sort -u >|"${HOME}/.mirror-postroll"
+
+  local -a sites
+  while IFS= read -r site; do sites+=("${site}"); done < <(cat "${HOME}/.mirror-postroll")
+  for site in "${sites[@]}"; do
+    printf "%s INFO: Processing %s\n" "${date}" "${site}" | tee -a "${FILE_MIRRORS_LOG}"
+    wget \
+      --convert-links \
+      --backup-converted \
+      --page-requisites \
+      --adjust-extension \
+      --no-parent \
+      --timestamping \
+      --tries=3 \
+      --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0' \
+      --execute robots=off \
+      --directory-prefix="${DIR_POSTROLL}" \
+      "${site}"
+  done
+
+  printf -- '----\n' | tee -a "${FILE_MIRRORS_LOG}"
+}
+
 main() {
   check_host
-  mirrors
+  mirror-postroll
+  mirror-sites
 }
 
 main
